In [1]:
import numpy as np
from tensorflow import keras


In [2]:
from keras.models import Sequential
from keras.layers import Dense,Activation,Flatten,Add
from keras.layers import Conv2D,MaxPooling2D,Dropout
from keras.utils import np_utils
from keras.datasets import mnist

Using TensorFlow backend.


In [3]:
(x_train,y_train),(x_test,y_test)=mnist.load_data()

In [4]:
x_train = x_train.reshape(x_train.shape[0], 28, 28,1)
x_test = x_test.reshape(x_test.shape[0], 28, 28,1)

In [5]:
x_train=x_train.astype('float32')
x_test=x_test.astype('float32')
x_train/=255
x_test/=255

In [6]:
y_train[:10]

array([5, 0, 4, 1, 9, 2, 1, 3, 1, 4], dtype=uint8)

In [7]:
y_train=np_utils.to_categorical(y_train,10)
y_test=np_utils.to_categorical(y_test,10)

In [8]:
y_train[:10]

array([[0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.]], dtype=float32)

In [9]:
from keras.layers import BatchNormalization,Activation

In [10]:
model=Sequential()
model.add(Conv2D(10,3,3,activation='relu',input_shape=(28,28,1)))
model.add(BatchNormalization())
model.add(Dropout(0.1))

model.add(Conv2D(16,3,3,activation='relu'))
model.add(BatchNormalization())
model.add(Dropout(0.1))

model.add(Conv2D(10,1,1,activation='relu'))
model.add(MaxPooling2D(pool_size=(2,2)))

model.add(Conv2D(16,3,3,activation='relu'))
model.add(BatchNormalization())
model.add(Dropout(0.1))

model.add(Conv2D(16, 3, 3, activation='relu'))#8                      # channel dimensions = 8x8x16    and Receptive field = 18x18
model.add(BatchNormalization())
model.add(Dropout(0.1))

# Performing 2dconvolution followed by BatchNormalization and Dropout
model.add(Conv2D(16, 3, 3, activation='relu'))#6                      # channel dimensions = 6x6x16    and Receptive field = 20x20
model.add(BatchNormalization())
model.add(Dropout(0.1))

# Performing 2dconvolution followed by BatchNormalization and Dropout
model.add(Conv2D(16, 3, 3, activation='relu'))#4                      # channel dimensions = 4x4x16    and Receptive field = 22x22
model.add(BatchNormalization())
model.add(Dropout(0.1))

model.add(Conv2D(10,4,4))

model.add(Flatten())

model.add(Activation('softmax'))


C:\Users\ideapad GAMIN\Anaconda3\envs\demoEnv\lib\site-packages\ipykernel_launcher.py:2: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(10, (3, 3), activation="relu", input_shape=(28, 28, 1...)`
  
C:\Users\ideapad GAMIN\Anaconda3\envs\demoEnv\lib\site-packages\ipykernel_launcher.py:6: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(16, (3, 3), activation="relu")`
  
C:\Users\ideapad GAMIN\Anaconda3\envs\demoEnv\lib\site-packages\ipykernel_launcher.py:10: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(10, (1, 1), activation="relu")`
  # Remove the CWD from sys.path while we load stuff.
C:\Users\ideapad GAMIN\Anaconda3\envs\demoEnv\lib\site-packages\ipykernel_launcher.py:13: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(16, (3, 3), activation="relu")`
  del sys.path[0]
C:\Users\ideapad GAMIN\Anaconda3\envs\demoEnv\lib\site-packages\ipykernel_launcher.py:17: UserWarning: Update your `Conv2D` call to the Keras

In [11]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_1 (Conv2D)            (None, 26, 26, 10)        100       
_________________________________________________________________
batch_normalization_1 (Batch (None, 26, 26, 10)        40        
_________________________________________________________________
dropout_1 (Dropout)          (None, 26, 26, 10)        0         
_________________________________________________________________
conv2d_2 (Conv2D)            (None, 24, 24, 16)        1456      
_________________________________________________________________
batch_normalization_2 (Batch (None, 24, 24, 16)        64        
_________________________________________________________________
dropout_2 (Dropout)          (None, 24, 24, 16)        0         
_________________________________________________________________
conv2d_3 (Conv2D)            (None, 24, 24, 10)       

In [15]:
# We are importing the Adam Optimizer
from tensorflow.keras.optimizers import Adam

# We are importing the learningratescheduler callback
from tensorflow.keras.callbacks import LearningRateScheduler
#Creating the "scheduler" function with two arguments i.e learningrate and epoch
def scheduler(epoch, lr):
    return round(0.003 * 1/(1 + 0.319 * epoch), 10)

#	LearningRate = LearningRate * 1/(1 + decay * epoch) here decay is 0.319 and epoch is 10.

# here we are compiling our model and using 'categorical_crossentropy' as our loss function and adam as our optimizer with learning rate =0.003 and metrics is accuracy
model.compile(loss='categorical_crossentropy', optimizer=Adam(), metrics=['accuracy'])

# Here we are traing our model using the data and using batch size of 128,number of epochs are 20 and using verbose=1 for printing out all the results.
# In the callbacks parameter we are using the LearningRateScheduler which takes two arguments scheduler function which we built earlier to reduce the learning rate in each decay and verbose =1
model.fit(x_train, y_train, batch_size=128, epochs=20, verbose=1, validation_data=(x_test, y_test))

Train on 60000 samples, validate on 10000 samples
Epoch 1/20
60000/60000 [==============================] - 23s 391us/step - loss: 0.4051 - accuracy: 0.8709 - val_loss: 1.0910 - val_accuracy: 0.7125
Epoch 2/20
60000/60000 [==============================] - 16s 270us/step - loss: 0.0971 - accuracy: 0.9701 - val_loss: 0.0529 - val_accuracy: 0.9832
Epoch 3/20
60000/60000 [==============================] - 9s 158us/step - loss: 0.0687 - accuracy: 0.9787 - val_loss: 0.0405 - val_accuracy: 0.9864
Epoch 4/20
60000/60000 [==============================] - 8s 137us/step - loss: 0.0545 - accuracy: 0.9830 - val_loss: 0.0328 - val_accuracy: 0.9889
Epoch 5/20
60000/60000 [==============================] - 8s 137us/step - loss: 0.0475 - accuracy: 0.9856 - val_loss: 0.0291 - val_accuracy: 0.9912
Epoch 6/20
60000/60000 [==============================] - 8s 138us/step - loss: 0.0405 - accuracy: 0.9875 - val_loss: 0.0392 - val_accuracy: 0.9882
Epoch 7/20
60000/60000 [==============================] - 8s

In [23]:
x_train[0]

array([[[0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ]],

       [[0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        

In [17]:
# Here we are evaluating our model using the test data and saving the results in score variable
score = model.evaluate(x_test, y_test, verbose=0)

In [18]:
score

[0.026691859318729257, 0.9921000003814697]

In [19]:
#Finally we are doing the predictions
y_pred = model.predict(x_test)

In [20]:
print(y_pred[:9])
print(y_test[:9])

[[1.99074313e-09 2.87421624e-08 3.21062243e-09 7.36303718e-07
  3.46654502e-07 1.43981813e-08 2.40393316e-10 9.99997973e-01
  4.12499646e-10 9.09997027e-07]
 [1.06056689e-07 2.02356678e-05 9.99978781e-01 6.73263472e-08
  2.80710855e-09 3.56098970e-11 7.04672743e-07 5.82076716e-08
  3.44259838e-08 8.75260107e-12]
 [2.53955790e-08 9.99983430e-01 1.67068393e-07 1.85925032e-07
  4.64579699e-07 7.73531610e-07 3.49689941e-07 1.32497171e-05
  1.37292909e-06 2.37635653e-08]
 [9.99939799e-01 1.75612980e-09 2.03975503e-07 1.94751841e-08
  5.25472499e-10 1.19660433e-08 5.86467941e-05 4.37455716e-09
  1.22538643e-06 8.61039240e-08]
 [3.31889140e-07 6.11404448e-06 7.17482385e-09 3.86855659e-09
  9.99584138e-01 2.32837738e-06 2.66344642e-07 1.46871741e-06
  6.25750616e-08 4.05223778e-04]
 [8.87294576e-08 9.99981761e-01 1.92399511e-07 1.19253897e-07
  1.67235157e-07 6.93358544e-08 1.14678905e-07 1.71734646e-05
  2.80646930e-07 1.07980540e-08]
 [6.98885061e-10 7.49029596e-06 1.91513621e-07 5.18650811e